Installing chrony removes systemd timesyncd
ansible-lockdown/UBUNTU20-CIS pull request #79
Opened 2023-04-18 19:47 UTC by kdebisschop

**Overall Review of Changes:**
Removes check of systemd-timesyncd when chrony is the configured time source

**Issue Fixes:**
#78

**Enhancements:**
Please list any enhancements/features that are not open issue tickets

**How has this been tested?:**
Used to configure an Ubuntu 20 test server. The step which previously failed (because systemd-timesyncd cannot be installed if chrony is) now runs successfully.

2023-04-20 15:24 UTC, MrSteve81 commented
Please make sure you properly sign off on your commits.  The DCO is failing because of that.

2023-04-20 21:38 UTC, kdebisschop commented
I saw that the note yesterday but have not yet had time to fix and do a force push. I hope to do that tonight. Thanks for the reminder.

2023-04-27 13:35 UTC, MrSteve81 commented
Added to my local machine and tested looks good.

2023-04-27 14:33 UTC, georgenalen approved these changes
Looks good!

2023-04-27 14:35 UTC, MrSteve81 reviewed
Looks Good

2023-04-27 14:37 UTC, MrSteve81 approved these changes
Added to my local machine and tested looks good.

2023-04-27 14:39 UTC, georgenalen requested changes
Commit is good, we just noticed their is no GPG signature.

2023-04-27 14:41 UTC, georgenalen commented
@kdebisschop, 
 He we just noticed that your commit has the signed-off-by, but does not have a gpg signature. For some reason DCO didn't pick up that missing element. Can you go back into your commit and make sure that commit is gpg signed? Your commit should have the green Verified next to it if it's gpg signed. 

-George

2023-04-27 21:46 UTC, kdebisschop commented
I have just force pushed the commit after running `git commit -S --amend`

I hope that is what you want

2023-05-01 15:01 UTC, georgenalen approved these changes
looks good!

2023-05-01 15:02 UTC, MrSteve81 approved these changes
Looks Good Thanks For Updating

2023-05-01 15:04 UTC, merged